### PR TITLE
Bringing custom code to master

### PR DESCRIPTION
**Pull request by tbranyen**
## Rewrite/refactor PR

I've rewritten the project, but following enough of the original code to attempt reconciliation with the original project.

This PR still needs unit tests before it should be merged.

Adds in:
- Standard ES6 (Symbol-based private properties/methods)
- Build process for legacy ES5
- Loads in Node/AMD/Browser
- Allows the VirtualList to be destroyed and recreated
- Adds in a refresh method to pass a new container and/or configuration
- A reverse boolean configuration option to provide a more chat-like experience. Rendering the start of the list at the bottom instead of the top.
- Fixes a bug with the reflow code interval that causes a race condition in which elements get erroneously removed, the fix is less code too, thank innerHTML!

TODO:
- [ ] Tests...
- [ ] Benchmarks...
- [x] Convert string heights to px, if 100% get calculated parent height
- [x] Make classes configurable
- [ ] Remove the need for the scroller element by some clever means
- [ ] Better JSdoc

### CODE REVIEW

**Comment by tbranyen** [comment]
This PR currently depends on a custom commit of diffHTML to work. But it works really well! Cycles through a smart-and-simply calculated container height value and determines the number of buffer elements to continuously reuse. DiffHTML applies only the most minimal patch between each item. The custom commit that allows this to work treats Document Fragments as identical to their respective parent.

Like this:

``` html
<ul id="container">
  <li>Some Default</li>
</ul>
```

``` js
var container = document.querySelector('#container');

// Pretend you wrote a service that returns a list of DOM Nodes for the list in a
// fragment.
//
// Something like this:
// <li>Some Default</li>
// <li>Some other Default</li>
var fragment = someOtherService.getDocumentFragment();

// Diff the children and ignore the NodeName and Attributes, just sync children.
diff.element(container, fragment);
```

This contrived example is exactly how this list diffing works though. It reuses the exact same elements and only diffs out the children and requires zero HTML parsing since we're dealing with DOM structures. This makes it incredibly performant. Since diffHTML heavily tests for memory leaks and contains well tested object and attribute pooling, there is very little worry about memory overhead.

I think this shows some real world potential for this kind of experiment.

**Comment by tbranyen** [comment]
Going to merge into master since people are interested.

**Comment by stevenvachon** [comment]
Why did "Netflix uses" cause `addEventListener('scroll'...)` to be removed?

**Comment by tbranyen** [comment]
Where did you see that? It's been years so I'm not entirely sure if that was in a comment or commit or if you saw it somewhere else.

**Comment by stevenvachon** [comment]
In https://github.com/tbranyen/virtual-list/pull/2/commits/cd91199c99714e947e258e8f443895a2fee1fb83

**Pull request merged**
